name: ppildo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_dotenv: 5.0.2
  dio: ^5.3.2
  flutter_spinkit: ^5.2.0
  shared_preferences: ^2.2.0
  dropdown_search: ^5.0.6
  intl: ^0.18.1
  syncfusion_flutter_datagrid: ^22.2.10
  webview_flutter: ^4.2.3
  url_launcher: ^6.1.12
  path_provider: ^2.1.0
  http: ^1.1.0
  flutter_pdfview: ^1.3.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
    
flutter_launcher_icons:
  android: launcher_icon
  image_path: assets/app_logo/app_logo.jpg
  ios: true

flutter: 
  assets:
    - assets/images/
    - assets/app_logo/
    - assets/icons/
    - assets/
    - .env

  uses-material-design: true

